# Generated by Django 2.0.5 on 2019-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_to_rachel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.TextField(default='I am empty'),
        ),
    ]
